### ISSUE TITLE
Any planes on ROS2 support?

### ISSUE THREAD

**Issue by chaitanyantr** [UTNuclearRoboticsPublic/netft_utils#13]
HI team,

thank you for maintaining the stack for force sensor reading for ROS1. I would be glad to know any planes on releasing the ros2 support for ATI netft sensor in future.

**Comment by AndyZe** [comment]
Hi @chaitanyantr, did you see that there are `iron` and `ros2` branches? Or do you mean, you want those released as debians?

**Comment by chaitanyantr** [comment]
oh that's great , I didn't see them. my bad closing the issue.

![image](https://github.com/user-attachments/assets/27673fd0-6ab1-43ab-bfad-be688dd34235)

**Comment by AndyZe** [comment]
I'll make `ros2` the default branch to avoid confusion in the future.
